name: trump
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  dio: ^5.6.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  sqflite: ^2.3.3+1
  path: ^1.9.0
  provider: ^6.1.2
  path_provider: ^2.1.4
  syncfusion_flutter_datepicker: ^26.2.10
  cr_calendar: ^1.2.1
  file_picker: ^8.1.2
  fluttertoast: ^8.2.8
  permission_handler: ^11.3.1
  record: ^5.1.2
  just_audio: ^0.9.40
  flick_video_player: ^0.9.0
  video_player: 2.9.1
    #lottie: ^3.1.2
  audio_session: ^0.1.21
  video_thumbnail: ^0.5.3
  web_socket_channel: ^3.0.1
  screen_brightness: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: tc
      fonts:
        - asset: fonts/iconfont.ttf

    - family: wk
      fonts:
        - asset: fonts/LXGWWenKaiMonoGBScreen.ttf
