import 'package:flutter/material.dart';

class TCIcons {
  static const IconData songguo =
      IconData(0xe8a4, fontFamily: 'tc', matchTextDirection: true);
  static const IconData patchCheckin =
      IconData(0xe69e, fontFamily: 'tc', matchTextDirection: true);
  static const IconData rename =
      IconData(0xe66b, fontFamily: 'tc', matchTextDirection: true);
  static const IconData cash =
      IconData(0xe619, fontFamily: 'tc', matchTextDirection: true);
  static const IconData lock =
      IconData(0xec26, fontFamily: 'tc', matchTextDirection: true);
  static const IconData lockOpen =
      IconData(0xec27, fontFamily: 'tc', matchTextDirection: true);
  static const IconData discoveryFill =
      IconData(0xe606, fontFamily: 'tc', matchTextDirection: true);
  static const IconData discovery =
      IconData(0xe607, fontFamily: 'tc', matchTextDirection: true);
  static const IconData homepageFill =
      IconData(0xe608, fontFamily: 'tc', matchTextDirection: true);
  static const IconData homepage =
      IconData(0xe609, fontFamily: 'tc', matchTextDirection: true);
  static const IconData listFill =
      IconData(0xe60a, fontFamily: 'tc', matchTextDirection: true);
  static const IconData list =
      IconData(0xe60b, fontFamily: 'tc', matchTextDirection: true);
  static const IconData mineFill =
      IconData(0xe60c, fontFamily: 'tc', matchTextDirection: true);
  static const IconData mine =
      IconData(0xe60d, fontFamily: 'tc', matchTextDirection: true);
  static const IconData recentNewsFill =
      IconData(0xe60e, fontFamily: 'tc', matchTextDirection: true);
  static const IconData recentNews =
      IconData(0xe60f, fontFamily: 'tc', matchTextDirection: true);
  static const IconData down =
      IconData(0xe610, fontFamily: 'tc', matchTextDirection: true);
  static const IconData up =
      IconData(0xe611, fontFamily: 'tc', matchTextDirection: true);
  static const IconData form =
      IconData(0xe612, fontFamily: 'tc', matchTextDirection: true);
  static const IconData horn =
      IconData(0xe613, fontFamily: 'tc', matchTextDirection: true);
  static const IconData search =
      IconData(0xe614, fontFamily: 'tc', matchTextDirection: true);
  static const IconData left =
      IconData(0xe617, fontFamily: 'tc', matchTextDirection: true);
  static const IconData choiceArticle =
      IconData(0xe61b, fontFamily: 'tc', matchTextDirection: true);
  static const IconData faq =
      IconData(0xe61c, fontFamily: 'tc', matchTextDirection: true);
  static const IconData luckyTurning =
      IconData(0xe61d, fontFamily: 'tc', matchTextDirection: true);
  static const IconData share =
      IconData(0xe61e, fontFamily: 'tc', matchTextDirection: true);
  static const IconData more =
      IconData(0xe61f, fontFamily: 'tc', matchTextDirection: true);
  static const IconData all =
      IconData(0xe620, fontFamily: 'tc', matchTextDirection: true);
  static const IconData articlesOfDailyUse =
      IconData(0xe621, fontFamily: 'tc', matchTextDirection: true);
  static const IconData cars =
      IconData(0xe622, fontFamily: 'tc', matchTextDirection: true);
  static const IconData comfortableClothes =
      IconData(0xe623, fontFamily: 'tc', matchTextDirection: true);
  static const IconData comment =
      IconData(0xe624, fontFamily: 'tc', matchTextDirection: true);
  static const IconData computer =
      IconData(0xe625, fontFamily: 'tc', matchTextDirection: true);
  static const IconData digitalAndPhone =
      IconData(0xe626, fontFamily: 'tc', matchTextDirection: true);
  static const IconData foodAndbeverage =
      IconData(0xe627, fontFamily: 'tc', matchTextDirection: true);
  static const IconData householdAppliances =
      IconData(0xe628, fontFamily: 'tc', matchTextDirection: true);
  static const IconData jewelry =
      IconData(0xe629, fontFamily: 'tc', matchTextDirection: true);
  static const IconData like =
      IconData(0xe62a, fontFamily: 'tc', matchTextDirection: true);
  static const IconData makeUp =
      IconData(0xe62b, fontFamily: 'tc', matchTextDirection: true);
  static const IconData others =
      IconData(0xe62c, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsDownLine =
      IconData(0xe62d, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsDown =
      IconData(0xe62e, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsLeftLine =
      IconData(0xe62f, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsLeft =
      IconData(0xe630, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsRightLine =
      IconData(0xe631, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsRight =
      IconData(0xe632, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsUpLine =
      IconData(0xe633, fontFamily: 'tc', matchTextDirection: true);
  static const IconData arrowsUp =
      IconData(0xe634, fontFamily: 'tc', matchTextDirection: true);
  static const IconData circle =
      IconData(0xe635, fontFamily: 'tc', matchTextDirection: true);
  static const IconData goodFill =
      IconData(0xe636, fontFamily: 'tc', matchTextDirection: true);
  static const IconData moreIf =
      IconData(0xe637, fontFamily: 'tc', matchTextDirection: true);
  static const IconData right =
      IconData(0xe638, fontFamily: 'tc', matchTextDirection: true);
  static const IconData buy =
      IconData(0xe63d, fontFamily: 'tc', matchTextDirection: true);
  static const IconData contactUs =
      IconData(0xe63e, fontFamily: 'tc', matchTextDirection: true);
  static const IconData ing =
      IconData(0xe63f, fontFamily: 'tc', matchTextDirection: true);
  static const IconData integral =
      IconData(0xe640, fontFamily: 'tc', matchTextDirection: true);
  static const IconData logistics =
      IconData(0xe641, fontFamily: 'tc', matchTextDirection: true);
  static const IconData luckyRecord =
      IconData(0xe642, fontFamily: 'tc', matchTextDirection: true);
  static const IconData money =
      IconData(0xe643, fontFamily: 'tc', matchTextDirection: true);
  static const IconData pengyouquan =
      IconData(0xe644, fontFamily: 'tc', matchTextDirection: true);
  static const IconData qqSpace =
      IconData(0xe645, fontFamily: 'tc', matchTextDirection: true);
  static const IconData record =
      IconData(0xe646, fontFamily: 'tc', matchTextDirection: true);
  static const IconData redEnvelope =
      IconData(0xe647, fontFamily: 'tc', matchTextDirection: true);
  static const IconData service =
      IconData(0xe648, fontFamily: 'tc', matchTextDirection: true);
  static const IconData shareOrder =
      IconData(0xe649, fontFamily: 'tc', matchTextDirection: true);
  static const IconData unlike =
      IconData(0xe64a, fontFamily: 'tc', matchTextDirection: true);
  static const IconData weixin =
      IconData(0xe64b, fontFamily: 'tc', matchTextDirection: true);
  static const IconData accountDetails =
      IconData(0xe64c, fontFamily: 'tc', matchTextDirection: true);
  static const IconData qq =
      IconData(0xe64d, fontFamily: 'tc', matchTextDirection: true);
  static const IconData invitation =
      IconData(0xe64e, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon002 =
      IconData(0xe64f, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon003 =
      IconData(0xe650, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon005 =
      IconData(0xe651, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon006 =
      IconData(0xe652, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon007 =
      IconData(0xe653, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon008 =
      IconData(0xe654, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon010 =
      IconData(0xe655, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon011 =
      IconData(0xe656, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon001 =
      IconData(0xe657, fontFamily: 'tc', matchTextDirection: true);
  static const IconData icon012 =
      IconData(0xe658, fontFamily: 'tc', matchTextDirection: true);
  static const IconData addressFill =
      IconData(0xe659, fontFamily: 'tc', matchTextDirection: true);
  static const IconData callPerson =
      IconData(0xe65a, fontFamily: 'tc', matchTextDirection: true);
  static const IconData emoticon =
      IconData(0xe65b, fontFamily: 'tc', matchTextDirection: true);
  static const IconData error =
      IconData(0xe65c, fontFamily: 'tc', matchTextDirection: true);
  static const IconData information =
      IconData(0xe65d, fontFamily: 'tc', matchTextDirection: true);
  static const IconData minusSign =
      IconData(0xe65e, fontFamily: 'tc', matchTextDirection: true);
  static const IconData pictureFill =
      IconData(0xe661, fontFamily: 'tc', matchTextDirection: true);
  static const IconData plus =
      IconData(0xe662, fontFamily: 'tc', matchTextDirection: true);
  static const IconData password =
      IconData(0xe663, fontFamily: 'tc', matchTextDirection: true);
  static const IconData iconfontEdit =
      IconData(0xe664, fontFamily: 'tc', matchTextDirection: true);
  static const IconData iconfontDazhuanpanCopy =
      IconData(0xe665, fontFamily: 'tc', matchTextDirection: true);
  static const IconData qqRound =
      IconData(0xe666, fontFamily: 'tc', matchTextDirection: true);
  static const IconData delete =
      IconData(0xe667, fontFamily: 'tc', matchTextDirection: true);
  static const IconData wechat =
      IconData(0xe668, fontFamily: 'tc', matchTextDirection: true);
  static const IconData help =
      IconData(0xe669, fontFamily: 'tc', matchTextDirection: true);
  static const IconData camera =
      IconData(0xe66, fontFamily: 'tc', matchTextDirection: true);
  static const IconData exp =
      IconData(0xe639, fontFamily: 'tc', matchTextDirection: true);
  static const IconData likeOutline =
      IconData(0xe618, fontFamily: 'tc', matchTextDirection: true);
}
